/* !!! Do not manually modify this file in the production stage !!!
 * This file is automatically created by MakeResBin.exe,
 * and used in the production stage.*/

#ifndef __RES_H_
#define __RES_H_

#define         RES_AUDIOPLAY0_BK       	0
#define         RES_AUDIOPLAY_BK        	1
#define         RES_CAM_INIT            	2
#define         RES_FRAME0              	3
#define         RES_FRAME1              	4
#define         RES_FRAME2              	5
#define         RES_FRAME3              	6
#define         RES_FRAME4              	7
#define         RES_FRAME5              	8
#define         RES_FRAME6              	9
#define         RES_FRAME7              	10
#define         RES_FRAME8              	11
#define         RES_GAMEMENU_BK         	12
#define         RES_GAMEMENU_BOLL       	13
#define         RES_GAMEMENU_MAZE       	14
#define         RES_GAMEMENU_PLANE      	15
#define         RES_GAMEMENU_PUSHBOX    	16
#define         RES_GAMEMENU_RB         	17
#define         RES_GAMEMENU_SNAKE      	18
#define         RES_GAME_BLOCK_BK0      	19
#define         RES_GAME_BLOCK_BK1      	20
#define         RES_GAME_BLOCK_BK2      	21
#define         RES_GAME_BLOCK_BK3      	22
#define         RES_GAME_BLOCK_ICON     	23
#define         RES_GAME_BLOCK_KNOCK    	24
#define         RES_GAME_BLOCK_MAP      	25
#define         RES_GAME_MAZE_MAP       	26
#define         RES_GAME_PLANE_AUDIO    	27
#define         RES_GAME_PLANE_ICON     	28
#define         RES_GAME_SNAKE_ICON     	29
#define         RES_GAME_SOKOBAN_ICON   	30
#define         RES_GAME_SOKOBAN_MAP    	31
#define         RES_GAME_TETRIS_BK      	32
#define         RES_GAME_TETRIS_ICON    	33
#define         RES_ICONSETTINGMENU     	34
#define         RES_ICON_BACKWARD       	35
#define         RES_ICON_FORWARD        	36
#define         RES_MAIN_BK             	37
#define         RES_MAIN_GAME_BK        	38
#define         RES_MAIN_MP3_BK         	39
#define         RES_MAIN_PHOTO_BK       	40
#define         RES_MAIN_PLAYBACK_BK    	41
#define         RES_MAIN_SETTING_BK     	42
#define         RES_MAIN_VIDEO_BK       	43
#define         RES_MP3FONT             	44
#define         RES_MUSIC_KEY_SOUND     	45
#define         RES_MUSIC_PHOTO_FOCUS   	46
#define         RES_MUSIC_PHOTO_TIME    	47
#define         RES_MUSIC_POWER_OFF     	48
#define         RES_MUSIC_POWER_ON      	49
#define         RES_MUSIC_TAKE_PHOTO    	50
#define         RES_OEM2UNI936          	51
#define         RES_OSD_SOURCE          	52
#define         RES_PALETTE             	53
#define         RES_PALETTE_GAME        	54
#define         RES_POWER_OFF           	55
#define         RES_POWER_ON            	56
#define         RES_RESFONT             	57
#define         RES_RESFONTIDX          	58
#define         RES_SETTINGMENU_BK      	59
#define         RES_STR_VERSION         	60
#define         RES_UNI2OEM936          	61
#define         RES_USBBAT_10           	62
#define         RES_USBBAT_100          	63
#define         RES_USBBAT_20           	64
#define         RES_USBBAT_30           	65
#define         RES_USBBAT_40           	66
#define         RES_USBBAT_50           	67
#define         RES_USBBAT_60           	68
#define         RES_USBBAT_70           	69
#define         RES_USBBAT_80           	70
#define         RES_USBBAT_90           	71
#define         RES_USBMODE_MSC         	72
#define         RES_USBMODE_PCCAM       	73

#endif
