#include"uiWin.h"

enum
{
	DATETIME_YEAR=0,
	DATETIME_MON,
	DATETIME_DAY,
	DATETIME_HOUR,
	DATETIME_MIN,
	DATETIME_SEC,
	DATETIME_OK,
	DATETIME_CANCEL,
	DATETIME_WIDGET_MANAGE
};
uint32 getDateTime1ResInfor(u16 id);

static widgetCreateInfor dateTime1Win[] =
{
	createFrameWin(Rx(70),Ry(42), Rw(180),Rh(142),R_COLOR_GRAY2,WIN_ABS_POS),
	createStringItem(DATETIME_YEAR, Rx(5), Ry(16), Rw(50), Rh(30),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_RED,0,R_COLOR_BLUE),
	createStringItem(DATETIME_MON,  Rx(65),Ry(16), Rw(50), Rh(30),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_YELLOW,0,R_COLOR_BLUE),
	createStringItem(DATETIME_DAY,  Rx(120), Ry(16), Rw(50), Rh(30),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_RED,0,R_COLOR_BLUE),
	createStringItem(DATETIME_HOUR,  Rx(35), Ry(56), Rw(30), Rh(30),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_RED,0,R_COLOR_BLUE),
	createStringItem(DATETIME_MIN,   Rx(75), Ry(56), Rw(30), Rh(30),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_RED,0,R_COLOR_BLUE),
	createStringItem(DATETIME_SEC,   Rx(115), Ry(56), Rw(30), Rh(30),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_RED,0,R_COLOR_BLUE),
	createStringItem(DATETIME_OK,    Rx(25), Ry(96), Rw(60), Rh(30),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_RED,0,R_COLOR_BLUE),
	createStringItem(DATETIME_CANCEL,Rx(95), Ry(96), Rw(60), Rh(30),strToResId(" "),ALIGNMENT_CENTER, R_COLOR_WHITE,0,R_COLOR_GRAY3,ALIGNMENT_CENTER, R_COLOR_RED,0,R_COLOR_BLUE),
	createWidgetManage(DATETIME_WIDGET_MANAGE,DATETIME_YEAR,DATETIME_CANCEL,getDateTime1ResInfor),
	widgetEnd(),
};



